version: '2.3'
services:
  apache:
    image: internetgruppen/hotel:php-5.6-apache
    mem_limit: 128m
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      APACHE_PORT: 8080
    expose:
      - 8080
    labels:
      - traefik.port=8080
    user: www-data
    read_only: true
    tmpfs:
      - /var/run
      - /var/lock
      - /tmp
    cap_drop:
      - ALL
    
networks:
  default:
    external:
      name: hotel
