version: '2.3'
services:
  apache:
    image: internetgruppen/hotel:php-5.6-apache
    mem_limit: 256m
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      APACHE_PORT: 80
    read_only: true
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini:ro
      - ./apache2.conf:/etc/apache2/apache2.conf:ro
    tmpfs:
      - /var/run
      - /var/lock
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - NET_BIND_SERVICE
    
networks:
  default:
    external:
      name: hotel
